export const root: string;
export const navLogo: string;
export const navBar: string;
export const outerContentContainer: string;
export const contentContainer: string;
export const contentRow: string;
export const menuColumn: string;
export const contentColumn: string;
export const footer: string;
